name: Audit

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    needs: [cargo-deny] # security-audit,
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.66.1"
          command: check ${{ matrix.checks }} -s
          arguments: --all-features
          log-level: warn